name: pn_code
description: "A new Flutter project."
publish_to: "none"
version: 1.0.8

environment:
  sdk: ^3.8.1

dependencies:
  animated_custom_dropdown: ^3.1.1
  animated_glitch: ^2.0.0+2
  animated_text_kit: ^4.3.0
  auto_size_text: ^3.0.0
  build_runner: ^2.4.13
  floating_navbar: ^3.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  get: ^4.7.2
  get_cli: ^1.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  icloud_storage: ^2.2.0
  multi_tap_action: ^2.1.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  # proximity_sensor: ^1.3.9
  # shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/audios/

  uses-material-design: true
